name: pull-request

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm install

      - name: Lint
        run: npm run lint
      - name: Test Node
        run: npm run test-node
      - name: Test browsers
        run: |
          sudo npx playwright install-deps
          npm run test-browser
